apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: JwtAuthentication
  annotations:
    github.com/project-slug: SaumyaBhushan/JwtAuthentication
spec:
  type: other
  lifecycle: unknown
  owner: guests
